### ISSUE TITLE
[Bug]: Not able to see live stream on Homekit

### ISSUE THREAD

**Issue by jlrivas3-hash** [homebridge-plugins/homebridge-eufy-security#710]
### What happened?

Good Evening, First thank you for the plug-in. Second, I'm fairly new to homebridge and plugins. Up to this point I've been very lucky when installing. So, I don't have a lot of experience trouble shooting, such as today.  Everything was straight forward, so I did not expect too much trouble. I just can't stream from homekit on iPhone, MacBook Air or AppleTV 4K. I'm getting "Snapshot Unavailable or No Response" from homekit. 

![Image](https://github.com/user-attachments/assets/e1bc374a-bc44-4b8d-80de-fd98fc48a1a3)

<img width="2038" height="1538" alt="Image" src="https://github.com/user-attachments/assets/f57c2cc8-b190-4467-9c97-28475cd8059a" />

### Device Type

Doorbell (Supported)

### Plugin Version

v3.0.x (Best Effort)

### HomeBridge Version

other (UnSupported)

### NodeJS Version

v20 (Supported)

### Operating System

Docker (UnSupported)

### Relevant log output

```shell
[8/24/2025, 12:32:39 PM] [TplinkSmarthome] [Front Door ] Setting Brightness to: 70
[08/24/2025, 12:32:49]  [EufySecurity]  INFO    T8214511250811C0 MOTION DETECTED (person detected)': false
[08/24/2025, 12:32:49]  [EufySecurity]  INFO    T8214511250811C0 MOTION DETECTED (motion detected)': false
[08/24/2025, 12:34:08]  [EufySecurity]  INFO    T8214511250811C0 MOTION DETECTED (person detected)': true
[08/24/2025, 12:34:08]  [EufySecurity]  INFO    T8214511250811C0 MOTION DETECTED (motion detected)': true
[8/24/2025, 12:34:08 PM] [TplinkSmarthome] [Front Door ] Setting On to: true
[8/24/2025, 12:34:08 PM] [TplinkSmarthome] [Front Door ] Setting Brightness to: 70
[08/24/2025, 12:34:18]  [EufySecurity]  INFO    T8214511250811C0 MOTION DETECTED (person detected)': false
[08/24/2025, 12:34:18]  [EufySecurity]  INFO    T8214511250811C0 MOTION DETECTED (motion detected)': false
[08/24/2025, 12:36:15]  [EufySecurity]  INFO    T8214511250811C0 MOTION DETECTED (person detected)': true
[08/24/2025, 12:36:15]  [EufySecurity]  INFO    T8214511250811C0 MOTION DETECTED (motion detected)': true
[8/24/2025, 12:36:23 PM] [TplinkSmarthome] [Front Door ] Setting On to: true
[8/24/2025, 12:36:23 PM] [TplinkSmarthome] [Front Door ] Setting Brightness to: 70
[08/24/2025, 12:36:25]  [EufySecurity]  INFO    T8214511250811C0 MOTION DETECTED (person detected)': false
[08/24/2025, 12:36:25]  [EufySecurity]  INFO    T8214511250811C0 MOTION DETECTED (motion detected)': false
[08/24/2025, 12:36:28]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 12:36:28]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 12:36:28]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 12:36:28]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 12:36:40]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 12:36:40]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 12:36:40]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 12:36:40]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 12:36:53]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 12:36:53]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 12:36:53]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 12:36:53]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 12:37:38]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 12:37:38]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 12:37:38]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 12:37:38]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 12:37:55]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 12:37:55]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 12:37:55]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 12:37:55]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 12:38:09]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 12:38:09]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 12:38:09]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 12:38:09]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[8/24/2025, 12:49:25 PM] [TplinkSmarthome.API] TCP 192.168.1.144:9999 Error: TCP Timeout after 15000ms
192.168.1.144:9999 {"smartlife.iot.common.emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:68:17)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
[8/24/2025, 12:49:25 PM] [TplinkSmarthome.API] [Front Door ] device.send() Error: TCP Timeout after 15000ms
192.168.1.144:9999 {"smartlife.iot.common.emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:68:17)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
[8/24/2025, 12:49:25 PM] [TplinkSmarthome] [Front Door ] emeter.getRealtime()
[8/24/2025, 12:49:25 PM] [TplinkSmarthome] Error: TCP Timeout after 15000ms
192.168.1.144:9999 {"smartlife.iot.common.emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:68:17)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
[8/24/2025, 12:49:25 PM] [TplinkSmarthome.API] TCP 192.168.1.205:9999 Error: TCP Timeout after 15000ms
192.168.1.205:9999 {"smartlife.iot.common.emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:68:17)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
[8/24/2025, 12:49:25 PM] [TplinkSmarthome.API] [Office] device.send() Error: TCP Timeout after 15000ms
192.168.1.205:9999 {"smartlife.iot.common.emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:68:17)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
[8/24/2025, 12:49:25 PM] [TplinkSmarthome] [Office] emeter.getRealtime()
[8/24/2025, 12:49:25 PM] [TplinkSmarthome] Error: TCP Timeout after 15000ms
192.168.1.205:9999 {"smartlife.iot.common.emeter":{"get_realtime":{}}}
    at Timeout._onTimeout (/homebridge/node_modules/homebridge-tplink-smarthome/node_modules/tplink-smarthome-api/src/network/tcp-socket.ts:68:17)
    at listOnTimeout (node:internal/timers:581:17)
    at processTimers (node:internal/timers:519:7)
[08/24/2025, 13:09:07]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 13:09:07]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 13:09:07]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 13:09:07]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 13:31:03]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 13:31:03]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 13:31:03]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 13:31:03]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[8/24/2025, 1:31:36 PM] [TplinkSmarthome] [Front Door ] Setting On to: false
[8/24/2025, 1:36:25 PM] [Homebridge UI] [homebridge-eufy-security] [4.3.7]      DEBUG   [server.js:132] Using bropats eufy-security-client library in version 3.2.0
[8/24/2025, 1:36:25 PM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[8/24/2025, 1:36:25 PM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[8/24/2025, 1:38:55 PM] [Homebridge UI] Changes to config.json saved.
[8/24/2025, 1:38:57 PM] [EufySecurity] Restarting child bridge...
[8/24/2025, 1:38:57 PM] Got SIGTERM, shutting down child bridge process...
[08/24/2025, 13:38:57]  [EufySecurity]  INFO    Finished shutdown!
[8/24/2025, 1:39:02 PM] [EufySecurity] Child bridge process ended
[8/24/2025, 1:39:02 PM] [EufySecurity] Process Ended. Code: 143, Signal: null
[8/24/2025, 1:39:09 PM] [EufySecurity] Restarting Process...
[8/24/2025, 1:39:10 PM] [EufySecurity] Launched child bridge with PID 27198
[8/24/2025, 1:39:10 PM] The plugin "homebridge-eufy-security" requires Node.js version of 20.11.0 || ^22 which does not satisfy the current Node.js version of v20.18.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[8/24/2025, 1:39:11 PM] Registering platform 'homebridge-eufy-security.EufySecurity'
[8/24/2025, 1:39:11 PM] [EufySecurity] Loaded homebridge-eufy-security v4.3.7 child bridge successfully
[8/24/2025, 1:39:12 PM] Loaded 1 cached accessories from cachedAccessories.0E48D9B251E3.
[8/24/2025, 1:39:12 PM] Homebridge v1.11.0 (HAP v0.13.1) (EufySecurity 9F56) is running on port 53849.
[08/24/2025, 13:39:20]  [EufySecurity]  ERROR   Error in stationAdded:

 Error  looks station but it's not could imply some errors! Type: 94. You can ignore this message.
error stack:
  • platform.ts EufySecurityPlatform.register_station
        platform.ts:689
  • platform.ts EufySecurityPlatform.addOrUpdateAccessory
        platform.ts:503
  • platform.ts EufySecurityPlatform.stationAdded
        platform.ts:570
[08/24/2025, 13:39:22]  [EufySecurity]  INFO    T8214511250811C0 is set to handle snapshots with cloud images. Snapshots might be older than they appear.
[08/24/2025, 13:39:22]  [EufySecurity]  ERROR   T8214511250811C0 could not fetch old snapshot: Error: No currentSnapshot
[08/24/2025, 13:39:22]  [EufySecurity]  INFO    Updating existing accessory: DEVICE T8214511250811C0
[08/24/2025, 13:39:37]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:39:55]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:39:57]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 13:39:57]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 13:39:57]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 13:39:57]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 13:39:59]  [EufySecurity]  INFO    No outdated cached accessories found.
[08/24/2025, 13:40:08]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:40:14]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 13:40:14]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 13:40:14]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 13:40:14]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[8/24/2025, 1:40:14 PM] [Homebridge UI] [homebridge-eufy-security] [4.3.7]      DEBUG   [server.js:132] Using bropats eufy-security-client library in version 3.2.0
[8/24/2025, 1:40:15 PM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[8/24/2025, 1:40:15 PM] [Homebridge UI] [homebridge-eufy-security] Incoming Request: /storedAccessories
[8/24/2025, 1:40:24 PM] [Homebridge UI] Changes to config.json saved.
[8/24/2025, 1:40:27 PM] [EufySecurity] Restarting child bridge...
[8/24/2025, 1:40:27 PM] Got SIGTERM, shutting down child bridge process...
[08/24/2025, 13:40:27]  [EufySecurity]  INFO    Finished shutdown!
[8/24/2025, 1:40:32 PM] [EufySecurity] Child bridge process ended
[8/24/2025, 1:40:32 PM] [EufySecurity] Process Ended. Code: 143, Signal: null
[8/24/2025, 1:40:39 PM] [EufySecurity] Restarting Process...
[8/24/2025, 1:40:40 PM] [EufySecurity] Launched child bridge with PID 27316
[8/24/2025, 1:40:40 PM] The plugin "homebridge-eufy-security" requires Node.js version of 20.11.0 || ^22 which does not satisfy the current Node.js version of v20.18.0. You may need to upgrade your installation of Node.js - see https://homebridge.io/w/JTKEF
[8/24/2025, 1:40:41 PM] Registering platform 'homebridge-eufy-security.EufySecurity'
[8/24/2025, 1:40:41 PM] [EufySecurity] Loaded homebridge-eufy-security v4.3.7 child bridge successfully
[8/24/2025, 1:40:41 PM] Loaded 1 cached accessories from cachedAccessories.0E48D9B251E3.
[8/24/2025, 1:40:42 PM] Homebridge v1.11.0 (HAP v0.13.1) (EufySecurity 9F56) is running on port 53849.
[08/24/2025, 13:40:49]  [EufySecurity]  ERROR   Error in stationAdded:

 Error  looks station but it's not could imply some errors! Type: 94. You can ignore this message.
error stack:
  • platform.ts EufySecurityPlatform.register_station
        platform.ts:689
  • platform.ts EufySecurityPlatform.addOrUpdateAccessory
        platform.ts:503
  • platform.ts EufySecurityPlatform.stationAdded
        platform.ts:570
[08/24/2025, 13:40:51]  [EufySecurity]  INFO    T8214511250811C0 is set to handle snapshots with cloud images. Snapshots might be older than they appear.
[08/24/2025, 13:40:51]  [EufySecurity]  ERROR   T8214511250811C0 could not fetch old snapshot: Error: No currentSnapshot
[08/24/2025, 13:40:52]  [EufySecurity]  INFO    Updating existing accessory: DEVICE T8214511250811C0
[08/24/2025, 13:40:52]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:41:02]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:41:12]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:41:22]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:41:28]  [EufySecurity]  INFO    No outdated cached accessories found.
[08/24/2025, 13:41:33]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:41:43]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:41:53]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:42:04]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:42:14]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:42:24]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:42:34]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:42:45]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:42:55]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:43:05]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:43:16]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:43:26]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:43:36]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:44:01]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 13:44:01]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 13:44:01]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 13:44:01]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 13:44:16]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:44:32]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 13:44:32]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 13:44:32]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 13:44:32]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 13:44:41]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:44:58]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 13:44:58]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 13:44:58]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 13:44:58]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 13:45:04]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:45:21]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 13:45:21]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 13:45:21]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 13:45:21]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 13:45:24]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:45:34]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:45:44]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:45:54]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:46:05]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:46:15]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:46:25]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:46:36]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:46:57]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:46:58]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 13:46:58]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 13:46:58]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 13:46:58]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 13:47:07]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:47:17]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:47:27]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:47:38]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:47:48]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:47:58]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:48:08]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:48:19]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:48:29]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:48:39]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:48:50]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:49:00]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:49:10]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:49:20]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:49:31]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:49:41]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:49:51]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:50:02]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:50:12]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:50:22]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:50:32]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:50:43]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:50:53]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:51:03]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:51:14]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:51:24]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:51:34]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:51:44]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:51:55]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:52:05]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:52:15]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:52:26]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:52:36]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:52:46]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 13:52:57]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:03:47]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:03:57]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:04:08]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:04:27]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:04:50]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 14:04:50]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 14:04:50]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 14:04:50]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 14:06:43]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:06:44]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:06:44]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:06:44]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:06:44]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:06:45]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:06:45]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:06:45]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:07:00]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 14:07:00]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 14:07:00]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 14:07:00]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[08/24/2025, 14:07:16]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:09:16]  [EufySecurity]  WARN    T8214511250811C0 No currentSnapshot available, using fallback unavailable snapshot image
[08/24/2025, 14:09:34]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 14:09:34]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 14:09:34]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 14:09:34]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
```

### config

```shell
Error  looks station but it's not could imply some errors! Type: 94. You can ignore this message.
error stack:
  • platform.ts EufySecurityPlatform.register_station
        platform.ts:689
  • platform.ts EufySecurityPlatform.addOrUpdateAccessory
        platform.ts:503
  • platform.ts EufySecurityPlatform.stationAdded
        platform.ts:570
[08/24/2025, 12:05:41]  [EufySecurity]  INFO    T8214511250811C0 is set to handle snapshots with cloud images. Snapshots might be older than they appear.
[08/24/2025, 12:05:41]  [EufySecurity]  ERROR   T8214511250811C0 could not fetch old snapshot: Error: No currentSnapshot
[08/24/2025, 12:05:41]  [EufySecurity]  INFO    Updating existing accessory: DEVICE T8214511250811C0
[08/24/2025, 12:06:18]  [EufySecurity]  INFO    No outdated cached accessories found.
[8/24/2025, 12:09:17 PM] [Homebridge UI] Starting terminal session.
[08/24/2025, 12:12:45]  [EufySecurity]  ERROR   T8214511250811C0 Livestream timeout: No livestream emitted within the expected timeframe.
[08/24/2025, 12:12:45]  [EufySecurity]  WARN    T8214511250811C0 If you are using Node.js version 18.19.1, 20.11.1, 21.6.2 or newer, this might be related to RSA_PKCS1_PADDING support removal.
[08/24/2025, 12:12:45]  [EufySecurity]  WARN    T8214511250811C0 Please try enabling "Embedded PKCS1 Support" in the plugin settings to resolve this issue.
[08/24/2025, 12:12:45]  [EufySecurity]  ERROR   T8214511250811C0 Unable to start the livestream: No livestream emitted... This may be due to Node.js compatibility issues. Try enabling Embedded PKCS1 Support in settings.
[8/24/2025, 12:12:59 PM] [Homebridge UI] Terminal session ended.
```

**Comment by Jarrydf13** [comment]
I am having the exact same issue, any updates? Mine is with a Eufy C30 doorbell

**Comment by tonycueva48** [comment]
I have the same issue. Wondering if there’s any update?

**Comment by rshideler** [comment]
Same error here too. I’ve tried all suggestions offered. Is this a config issue or a plugin error.

**Comment by pds11001** [comment]
Any updates on this issue? I have doorbell C31 and same issues. Connection to two Solocams S220 works great. The issue on the doorbell seems localized to the video stream as others appear to be.

Thanks for the great plug-in!

**Comment by lenoxys** [comment]
Hi,

Thanks for reporting this issue.

Could you please test the latest beta version (**4.4.2-beta.7**) we've released? You can install it with:

```
npm install homebridge-eufy-security@4.4.2-beta.7
```

Make sure to use latest nodes 24.5+

This beta works with the latest bropat eufy-security-client library, which includes a lot of fixes concerning the Homebase communication. The PKCS1 issue you're encountering should no longer require the \`enableEmbeddedPKCS1Support\` workaround — **please make sure to disable it** (set \`\"enableEmbeddedPKCS1Support\": false\` or remove it from your config) when testing.

Let me know if this resolves your livestream issue!

**Comment by allen0120dev** [comment]
[homebridge.log.txt](https://github.com/user-attachments/files/25405709/homebridge.log.txt)

Hello I am still seeing this issue using homebridge-eufy-security 4.4.2-beta.7. This is with and without enabling Embedded PKCS1 Support.
Are there another suggested tests to run here by chance?

**Comment by lenoxys** [comment]
Can you try the latest beta ?

**Comment by lenoxys** [comment]
Can you try the new GA 4.4.2 version ?

**Comment by lenoxys** [comment]
hello can you test on 4.5.1 latest beta ?

**Comment by tarun101** [comment]
I can confirm that this issue does not occur on 4.6.0 beta but does occur on 4.5.1 production release. I tested it with:
- S3 Pro connected to homebase 3
- Doorbell E340 connected via chime

**Comment by lenoxys** [comment]
**This project is currently frozen.**

The plugin relies on [`eufy-security-client`](https://github.com/bropat/eufy-security-client), which its maintainer has **deprecated**. Eufy has moved its apps to a new **"Mega"** protocol, and a brand-new library is being built against it. All development effort is going there.

What this means for now:
- ✅ The current version keeps working as-is for devices still on the old protocol.
- 🧊 No new features or new device support can be added.
- 🩹 Only strictly necessary fixes for critical breakages will be considered.
- 🚀 Effort is focused on the new Mega-protocol library first. Work to adopt it in this plugin **has not started yet**.

**ETA:** work on this plugin is not expected to begin before **mid-August 2026**, and only once the underlying library is ready.

Because of this, I'm closing existing issues and pull requests to reflect the current status. This is not a reflection on your report — I simply cannot action it right now.

Please watch the repository and the upstream [deprecation notice](https://github.com/bropat/eufy-security-client) for updates.

💬 For questions and discussion, join us on [Discord](https://discord.gg/jc8FSjqQAN).

Thank you for your patience. 🙏
